### ISSUE TITLE
Routable content, disabling md-tabs-content-wrapper?

### ISSUE THREAD

**Issue by manosbatsis** [cogniteev/ember-paper-tabs#4]
I'm using the component to display routable content per tab using the onSelect in a template like this:

```
{{#paper-tabs centerTabs=true borderBottom=true as |tabs|}}
   {{tabs.tab label="Settings" onSelect=(action (transition-to "spaces.space.index" model))}}
   {{tabs.tab label="Members" onSelect=(action (transition-to "spaces.space.members" model))}}
   {{tabs.tab label="Billing" onSelect=(action (transition-to "spaces.space.billing" model))}}
{{/paper-tabs}}
{{outlet}}
```

This works just fine but creates a redundant md-tabs-content-wrapper etc. Is there a way to disable the output of the content wrapper or properly use it to display the routable content?

**Comment by panthony** [comment]
Hi @manosbatsis

It's not possible with this addon at the moment.

I started implementing this for the PR to ember-paper (https://github.com/miguelcobain/ember-paper/pull/578/commits/31b9b9581ac58fb252744bf8b20377d7eb3f37fc) but the upgrade to a newer version of angular broke a number of things and I can't afford more time to it right now.

I'll take another look when I'll have more time on my hand but any help would be appreciated.

**Comment by manosbatsis** [comment]
This hack is usable:

```js
  this.route('spaces', function() {
    this.route('new');

    this.route('space', {path: ':space_id'}, function() {
      this.route('settings');
      this.route('members');
      this.route('billing');
      this.route('membership-requests');
    });
```

```
<!-- /app/templates/spaces/space.hbs -->
{{#paper-tabs class='md-no-tab-content' centerTabs=true borderBottom=true as |tabs|}}
   {{tabs.tab label="Settings" onSelect=(action (transition-to "spaces.space.settings" model))}}
   {{tabs.tab label="Members" onSelect=(action (transition-to "spaces.space.members" model))}}
   {{tabs.tab label="Requests" onSelect=(action (transition-to "spaces.space.membership-requests" model))}}
   {{tabs.tab label="Billing" onSelect=(action (transition-to "spaces.space.billing" model))}}
 {{/paper-tabs}}
 <md-tabs-content-wrapper style="display:none"/>

<div class="layout-fill layout-row layout-align-center-start ">
  {{outlet}}
</div>
```

**Comment by beastmst** [comment]
when go directly to the route, the tab seems not to set to active.. any solution for it?

**Comment by panthony** [comment]
Hi, I suggest using the components from ember-paper directly as it was merged in master.

http://miguelcobain.github.io/ember-paper/#/components/tabs/nested-route

This addon is not active anymore
