### ISSUE TITLE
Tabs rendered as sequential text on page

### ISSUE THREAD

**Issue by acgrama** [cogniteev/ember-paper-tabs#5]
Hi,

I have used some code from your dummy application to try out the ember-paper-tabs:
```
  {{#paper-card as |card|}}
    {{#paper-toolbar as |toolbar|}}
      {{#toolbar.tools}}
        <h2>Dynamic Height</h2>
      {{/toolbar.tools}}
    {{/paper-toolbar}}

  {{#paper-tabs dynamicHeight=true as |tabs|}}
    {{#tabs.tab label="ONE" as |tab|}}
      {{#card.content class="md-padding"}}
        <h1 class="md-display-2">Tab One</h1>
        <p>...</p>
      {{/card.content}}
    {{/tabs.tab}}
    {{#tabs.tab label="TWO" as |tab|}}
      {{#card.content class="md-padding"}}
        <h1 class="md-display-2">Tab Two</h1>
        <p>...</p>
      {{/card.content}}
    {{/tabs.tab}}
    {{#tabs.tab label="THREE" as |tab|}}
      {{#card.content class="md-padding"}}
        <h1 class="md-display-2">Tab Three</h1>
        <p>...</p>
      {{/card.content}}
    {{/tabs.tab}}
  {{/paper-tabs}}

{{/paper-card}}

```
But the rendered result looks like this:
![tabs](https://user-images.githubusercontent.com/1415729/28310170-d56e3810-6bab-11e7-9caa-1eb32ca4e94c.jpg)

Do you have any idea what might be going on?
Thanks a lot!

**Comment by panthony** [comment]
Did you include the scss?

In your `app.scss`:

`@import "ember-paper-tabs";`

But be aware that they are issues with this current version and I do not have time at the moment to fix them.

This addon was a temporary solution while the PR is finalized and merged in main repository:

https://github.com/miguelcobain/ember-paper/pull/578

**Comment by acgrama** [comment]
Ah yes, that might be it, sorry for the trouble! (working with pre-existing code & styling, forgot to check that the scss was there...)

I'm glad to hear this will be a part of the stable build.
