### ISSUE TITLE
npm deprecate

### ISSUE THREAD

**Issue by miguelcobain** [cogniteev/ember-paper-tabs#6]
Thanks for adding the deprecation notice on the README.

You should also run npm deprecate (https://docs.npmjs.com/cli/deprecate) to let users know of that in the cli, with a message containing the minimum ember-paper version that users should have to have tabs (`1.0.0-beta.1`).

**Comment by panthony** [comment]
Thanks for the hint !

```bash
 % npm install ember-paper-tabs
npm WARN deprecated ember-paper-tabs@0.0.1: This addon is no longer active. The component paper-tabs is now available in ember-paper starting with version 1.0.0-beta.1
```
